### PR TITLE
Fix cloud-init config and sudo commands.

### PR DESCRIPTION
**Pull request by nan-coupa**
Azure WALinux agent does not support an Provisioning.Agent called `cloud-auto`, it should be `cloud-init`. The `sudo cat` and `sudo echo` commands have been revised to use sudo tee to write the files because the redirect (> or >>) is still under the user instead of root.

### CODE REVIEW

**Comment by Court72** [comment]
@nan-coupa 

Thank you for your contribution. Would you take a moment to sign the [Contributor License Agreement (CLA)](https://github.com/MicrosoftDocs/azure-compute-docs/pull/39#issuecomment-2361340813)? After the CLA is signed, someone can review your pull request. Thanks!

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by nan-coupa** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@srijang, @vamckMS, @anhvoms 

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by vamckMS** [comment]
@anhvoms does the changes look good to you?

**Comment by anhvoms** [comment]
> @anhvoms does the changes look good to you?

@vamckMS changes look good.

**Comment by vamckMS** [comment]
#signoff

**Comment by vamckMS** [comment]
@Court72 could you please help merge this PR
#sign-off

**Pull request merged**
