### PR TITLE
Update redhat-create-upload-vhd.md

### PR DESCRIPTION
**Pull request by mries**
Re-worked document, hanges include:
1. Re-formated versions by hypervisor type and made  collapsable.  This was done to reduce the business of  document only showing chosen scenario

2. included RHEL 9 configuration. Added it to the existing RHEL 8 as the given steps to prepare VM haven't changed.

3. updated syntax for clarity.

4. removed references to RHEL 6 as the "Extended life cycle support (ELS) add-on ends" has ended.
https://access.redhat.com/product-life-cycles?product=Red%20Hat%20Enterprise%20Linux,OpenShift%20Container%20Platform%204

### CODE REVIEW

**Comment by mries** [comment]
Complete re-work of the document.  having a review with my group.

**Comment by Court72** [comment]
@srijang, @vamckMS, @anhvoms 

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by vamckMS** [comment]
Looks good to me - #sign-off

**Comment by Court72** [comment]
Thanks, @vamckMS. The new commits add functionality that needs to be reviewed on staging to ensure that the content renders as expected. To do this, the commits must be moved to the private repo. 

Can you move the commits? See [Pull public commits to the private repo for updates, staging, publication](https://review.learn.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication) for details. Let us know if you need the PR Review Team's help.

Thanks.
#hold-off

**Comment by vamckMS** [comment]
> Thanks, @vamckMS. The new commits add functionality that needs to be reviewed on staging to ensure that the content renders as expected. To do this, the commits must be moved to the private repo.
> 
> Can you move the commits? See [Pull public commits to the private repo for updates, staging, publication](https://review.learn.microsoft.com/en-us/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication) for details. Let us know if you need the PR Review Team's help.
> 
> Thanks. #hold-off

@Court72 is this action item (to move to pvt repo) for me or for @mries ?

**Comment by Court72** [comment]
@vamckMS - the action is for you. Thanks for checking!

**Comment by vamckMS** [comment]
@Court72 I was under the impression that all MS employees have the ability to create PRs on the private repo is that not the case?If so, curious on why I am being asked to move these to the pvt repo? is it because I own the doc now (after Srijan)?

**Pull request closed without merging**
