### PR TITLE
Update ebdsv5-ebsv5-series.md

### PR DESCRIPTION
**Pull request by eehindero**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@ju-shim 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by eehindero** [comment]
#sign-off

**Comment by eehindero** [comment]
@Jak-MS Please can you provide an update on the file changes? It's been a week, and the changes have not reflected in the docs. Thank you.

**Comment by ttorble** [comment]
@eehindero 

Only the listed author can sign off on updates made in the public repo. You can request approval from the author @ju-shim or you can close this PR and make the change in the private repo `azure-compute-docs-pr`. 

Read about [authors working in the public repo](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=main) for more information. 

If you need help getting set up to work in the private repo, see [Get started contributing to the Microsoft Learn platform](https://review.learn.microsoft.com/help/get-started/?branch=main&tabs=learn). 

Thanks

**Comment by Jak-MS** [comment]
hi @eehindero - closing this considering you opened the identical PR in the private repo (as @ttorble recommended). Thanks

https://github.com/MicrosoftDocs/azure-compute-docs-pr/pull/771

**Pull request closed without merging**
