### PR TITLE
Update run-command-managed.md

### PR DESCRIPTION
**Pull request by Delizald**
Changed code example 'GET' to  'PUT' as per the description of the REST API call

### CODE REVIEW

**Comment by Delizald** [comment]
Actually now that I think about it. I'm trying to use 'PUT' for this method but the response is "Method not allowed" so this should be POST

**Comment by ttorble** [comment]
@ju-shim 

Can you review the proposed changes?

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ju-shim** [comment]
#sign-off

**Comment by ju-shim** [comment]
Taking care of this in an internal PR, #please-close and thank you.

**Pull request closed without merging**
