### PR TITLE
Fix debian create upload vhd.md

### PR DESCRIPTION
**Pull request by alee-ntap**
This PR contains four commits:
* Do not limited to create "Stable" version of Debian VHD.
* Replace obsoleted script with up to dated article for upload a VHD to Azure or copy a managed disk to another region - Azure CLI.
* Replace the obsoleted way. Now check the image.info to verify packages installed in the image instead.
* Update path in the example script that support builds on multiple releases.

### CODE REVIEW

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
@alee-ntap - we can't review and merge your PR until you sign the CLA. Instructions are here: https://github.com/MicrosoftDocs/azure-compute-docs/pull/23#issuecomment-2362158370

**Comment by Jak-MS** [comment]
@srijang - after @srijang agrees to the CLA ... 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by anhvoms** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@alee-ntap - we can't merge this until you agree to the CLA - instructions are here:  https://github.com/MicrosoftDocs/azure-compute-docs/pull/23#issuecomment-2394299550 

thanks

**Comment by ShannonLeavitt** [comment]
@alee-ntap  - Can you sign the CLA as described above?

**Comment by ShannonLeavitt** [comment]
@anhvoms - It appears that @alee-ntap is not receiving notifications for this PR. If we don't hear back from the contributor soon, we will need to close the PR. Please make any necessary content changes via the private repo.

**Comment by ShannonLeavitt** [comment]
@anhvoms - Unfortunately, without a CLA agreement from @alee-ntap we can't merge this PR. We will close the PR now, but if @alee-ntap gets this message later, they can at-mention MicrosoftDocs/public-repo-pr-review-team and ask us to reopen the PR.

**Pull request closed without merging**
