### PR TITLE
Update Ultra Disk availability

### PR DESCRIPTION
**Pull request by lilyychen96**
- France Central + South Africa North to 3 AZs
- Move out AZ regions from "Single VMs" to "One availability zone"
- "Single VMs" to "Regional", non-AZ regions

### CODE REVIEW

**Comment by v-dirichards** [comment]
@roygara 

Can you review the proposed changes?
 
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.
 
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by lilyychen96** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@lilyychen96 - it looks like you have access to the private repo and if so, you should be working in that repo. You can opt to keep this PR open and wait for sign off and/or approval by @roygara ... or you can open a new PR in the private repo and close this one. In the private repos you can sign off on your own prs.  Thanks.

**Comment by lilyychen96** [comment]
Thanks @Jak-MS, I will move my changes to the private repo.

**Pull request closed without merging**
