### PR TITLE
Update tutorial-custom-images.md and change `--managed-image` to `--virtual-machine` parameter.

### PR DESCRIPTION
**Pull request by Dxaz**
--managed-image need to get replaced with --virtual-machine as it takes a Virtual Machine ID given in the steps above while --managed-image requires a manged image resource ID.

Using managed-image parameter here will throw an error:
 The gallery image version source id: '/subscriptions/0000-0000-0000-0000/resourceGroups/myGalleryRG/providers/Microsoft.Compute/virtualMachines/myVM' must be specified in 'galleryImageVersion.properties.storageProfile.source.virtualMachineId'.
Target: galleryImageVersion.properties.storageProfile.source

az sig image-version create states this in the documentation:
https://learn.microsoft.com/en-us/cli/azure/sig/image-version?view=azure-cli-latest#az-sig-image-version-create-optional-parameters

As well as the examples:

Add a new image version with encryption using a disk encryption set. Encryption is applied to each disk that is a part of the image version.

Azure CLI

Copy

Open Cloud Shell
az sig image-version create --resource-group MyResourceGroup \
--gallery-name MyGallery --gallery-image-definition MyImage \
--gallery-image-version 1.0.0 \
--virtual-machine /subscriptions/00000000-0000-0000-0000-00000000xxxx/resourceGroups/imageGroups/providers/Microsoft.Compute/virtualMachines/MyVM \
--target-regions westus=2=standard eastus \
--target-region-encryption WestUSDiskEncryptionSet1,0,WestUSDiskEncryptionSet2 \
EastUSDiskEncryptionSet1,0,EastUSDiskEncryptionSet2

### CODE REVIEW

**Comment by Jak-MS** [comment]
@mattmcinnes 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Dxaz** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@mattmcinnes - nudge. this has been waiting a while... can you take a look ?  thanks.

**Comment by Dxaz** [comment]
Hey @mattmcinnes can I get you take a quick look, it'll take 10 minutes of time to look and test to verify the change.

**Comment by Dxaz** [comment]
@Jak-MS any updates from @mattmcinnes ?

**Comment by Jak-MS** [comment]
sent email to @mattmcinnes

**Comment by mattmcinnes** [comment]
Apologies for the delay on this! Tested and confirmed functional

**Comment by mattmcinnes** [comment]
#sign-off

**Pull request merged**
