### PR TITLE
Update windows-in-place-upgrade.md

### PR DESCRIPTION
**Pull request by AmandaAZ**
Add a note to this article according to Scott Roberts's comment in https://dev.azure.com/KMOps/ContentExperience/_workitems/edit/1351, to align with this article "[In-place upgrade for supported VMs running Windows in Azure](https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/windows/in-place-system-upgrade)".

### CODE REVIEW

**Comment by AmandaAZ** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
@ju-shim

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by AmandaAZ** [comment]
@ju-shim Could you review and merge this PR? Thanks.

**Review by ju-shim — APPROVED** [review]

**Comment by ju-shim** [comment]
#sign-off

**Pull request merged**
