### PR TITLE
updated the dynamic scope limits

### PR DESCRIPTION
**Pull request by ApnaLakshay**

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@ju-shim

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ApnaLakshay** [comment]
#sign-off

**Comment by ApnaLakshay** [comment]
@ju-shim Let me know if you have any questions regarding the change.

**Comment by ApnaLakshay** [comment]
#sign-off

**Comment by ApnaLakshay** [comment]
@ju-shim Can you please provide us with the sign off on this PR as this is a minor change, big impact work that the team worked on and the changes needs to be reflected on the portal.

**Pull request closed without merging**
